name = "RedstoneToolkit"
author = "Scorpio"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "035e1cfcdfd3278f1fa86dc2ca9eea0e2fc2f287c3a2bbd50b2623ca712cfc2d"

[versions]
fabric = "0.19.1"
minecraft = "26.1"

[options]
acceptable-game-versions = [
    "26.1-pre-1",
    "26.1-rc-2",
]
