name = "RedstoneToolkit"
author = "Scorpio"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "977f5bfe5bfe702e83922fe668e0c228c93fe2a38aafdb554543b1701db7aa0e"

[versions]
fabric = "0.19.1"
minecraft = "26.1"

[options]
acceptable-game-versions = [
    "26.1-pre-1",
    "26.1-rc-2",
]
