name = "RedstoneToolkit"
author = "Scorpio"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4028b481f639f4805e49031275925fe99d6b7775e18e0795e5e35f9bddcb1d8b"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
