name = "RedstoneToolkit"
author = "Scorpio"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a90a1ec408e6a79b4fdfbcf2f3afd02a7346e9dfcc7eb9e7048d0242a07f7886"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
