name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a793ca8a7337de574ea4bca4707e4c2e2b0122ef7a1a446cb0505b32b6e6d0a"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
