name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d65ac0f1d0ae5ea0d69adc472aa98b0da689c0ec34150a813e641dde60bf60f"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
