name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac5cf5f52d65fe89196718b165bc40208a9dd9188db3e28d75273f07a61fc946"

[versions]
fabric = "0.19.1"
minecraft = "1.20.6"
