name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af4b2a4ea1d228a3d48ef42e5c7df3dfd5d8ece1e08761fe75b4014b2ccddbb4"

[versions]
fabric = "0.19.5"
minecraft = "1.20.6"
