name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08536817471f0835e23456affd860b286f4639d51d9d46ecfc758f0e863fd47a"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
