name = "RedstoneToolkit"
author = "Scorpio"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a967e62cd17fa7467a42b3a05e96d9ceea744f4c3282168320cb9286e7146d5"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
