name = "RedstoneToolkit"
author = "Scorpio"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a7942ef52e76f9a3489765171a795c657b6d6fbbf143828a3e9870de5850fdf"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
