name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dff51de00c2d837afc5ca6c03ba3aaa7b39704923658152051fe3e3462b5d33"

[versions]
fabric = "0.19.3"
minecraft = "1.21"
