name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82874433f6aebec176a467d84f07dce961882e04efe8c9e4a6b52da2566e051b"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
