name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd2ac8f0058855e409ab5624d6569a8308cb7fd1bc3a4299a127b9eed8e1ba9"

[versions]
fabric = "0.19.1"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
