name = "RedstoneToolkit"
author = "Scorpio"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58b46263995074fd086f2221387b6133585aabd35721550764f3444a4d2b5790"

[versions]
fabric = "0.19.1"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
