name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2288a9d738a15fc0cd8ef0012127c65094d80f13c701b6739f45d6b37171a6a"

[versions]
fabric = "0.19.3"
minecraft = "1.17.1"
