name = "RedstoneToolkit"
author = "Scorpio"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51920e856a6cde4ce5c0555288c6693488c07dde24aff3c84fdf659b393ba2b4"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
