name = "RedstoneToolkit"
author = "Scorpio"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb848143fb18f462b7f8258327037250b4a9dd15ce0ec3c7f52410ec7dd91ca5"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
