name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e785d6c0132ce122acb6ef78adf531125374740ebeb9afbedf550495b3672d30"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
