name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48d0b875e980ab8e649e0eadef0d5c9e35862a85d7cd6949de0a7e80955400d2"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
