name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f203d21b7131ae4077a2e1cf9fdb8101eceba83e0884bcfc544c14c277c5988"

[versions]
fabric = "0.19.1"
minecraft = "1.20.6"
