name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a03345b2bec5e53ba326f048d1d3996abb1cabb8e287451fcd6c9b4c2b36796c"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
