name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df7ec1e54dc0fb81ab5cfe511ed11b89c49b9d0268c33e220f1021aa1b26991"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
