name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40eeffd82ca08649f2eb5854e100db5703a91f04ed585f69dccaa4f5c22174d5"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
