name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3a2919a50ca7f13cd38bfc43a1d01da39bf84cb32a1d949e4c4cb91384b3502"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
