name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9867b473beba7a9cef0db09e4471357f41b81413d4c04174963ae736cadc6eb"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
