name = "RedstoneToolkit"
author = "Scorpio"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be0e434ac13186d6778f83599d604b0d3aef5daa54d36530726a33aec05a4a71"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
