name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d112e777a896b5a2e9fae25f697130a10db3108a90d6c4085291cd0a48b6e65"

[versions]
fabric = "0.19.3"
minecraft = "1.17.1"
