name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17cc5954c33fcfd06b0e21b4c877e97f6b5456d8d7534b98bc1e45295a105fba"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
