name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21e54dc11172ac43139c925096f4c3f21062d806a3dc327a98e7d587b463d230"

[versions]
fabric = "0.19.3"
minecraft = "1.17.1"
