name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1735f63ffa86c151311e45203d23b2dde01d7c0fed4f4d5bdafbfcce93082a33"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
