name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ef4e28bef23c14a6f1245dff40d0a0b745c507da1bd992a405acd0b05838daf"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
