name = "RedstoneToolkit"
author = "Scorpio"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7332c005078240d5987dae47546d8cb2b3b7930d6c33113116554811bdce0c31"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
