name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dd89c2a7d0f0bcf7cd90f5fb4643d2cdb097509c28317dd2c2832578926830a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
