name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af20b1234c71701c265b7146acab05d0ad722fe35c3caade47244b60f7a353f9"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
