name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89fde85d46f2b0eabcef01991a8058aa6cc8ae811d3033031f111286f7c14546"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
