name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9976afdd39dba9c0e0f26a363ac35311463f47318eef4f1fbe24e85fb3a4eb1d"

[versions]
fabric = "0.19.1"
minecraft = "1.18.2"
