name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e79f72da4cbcdf1c04df2dbb161dc080212da5884528a977145146de2596ebfb"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
