name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d93ae50a955d837e435bf2ffaef8e80576602869aef78627209da5a6eebdf5d4"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
