name = "RedstoneToolkit"
author = "Scorpio"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a063d94d94c9aa336b3241b09778d2e4909ff1997f76609ca68aab1cf690b50"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = [
    "1.21.10",
]
