name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c67e2028367a20e2fe6c614b62a7db1b8eb26d143a86b7c411b9716b663f353"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
