name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20775012ecc9375e72490d7dc246f31c58308d706db28fda508909aa85068066"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
