name = "RedstoneToolkit"
author = "Scorpio"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc0c4ca3f7841817443d9bd610e67dc2d33dbfc5038ecec8cb03891fa3aaadd8"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
