name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1ce908b984e6dbd772233077a64471e5a95affbf599e5662a9fece4a49b899d"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"
