name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fb3f13f8127c2cceb8c7fca8f6e0d5337323ee5cc4fe14bec072d22c12d8917"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
