name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2efa6ed4fa876f2b54d60713e0aed3df1f1f188ca34abf857d94130323350de9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
