name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea08f8c9c55cb337e956185a5d34db1e63d0fefae1d5de8ec9674946bd056a74"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-6"
