name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b7edef476aa2f421d7cf83160487bf62f8435435c4eb9a792f5e244f64511e9"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-7"
