name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79d43e991dbd66a0c579fe3077c8ae3e3c79d47d05b13d33b48d7022975b7124"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
