name = "RedstoneToolkit"
author = "Scorpio"
version = "0.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caed3383cb5aae09278771ae041618b8d9a6ab8248ffe02aba103c082dfa67f7"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
