name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09e44d5316a0b9cf9a9977f72f7f3f66795a03dab8158a68fba8c38e000fcd23"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
