name: release
on: workflow_dispatch

jobs:
  find_matrix:
    runs-on: ubuntu-latest
    outputs:
      json_str: ${{ steps.output-json.outputs.json_str }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: pip requirements
        run: 'pip install PyGithub'
      - name: generated json
        run: python .github/workflows/script/matrix.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: output json
        id: output-json
        run: |
          echo "json_str=$(cat data.json)" >> $GITHUB_OUTPUT

  create_release:
    runs-on: ubuntu-latest
    needs: find_matrix
    if: ${{ fromJSON(needs.find_matrix.outputs.json_str).should_create }}
    strategy:
      matrix:
        tag: ${{ fromJSON(needs.find_matrix.outputs.json_str).create }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: create
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ format('Redstone Toolkit v{0}', matrix.tag) }}
          tag_name: ${{ format('release/{0}', matrix.tag) }}
          body_path: changelog.md
          token: ${{ secrets.GH_TOKEN }}

  modrinth_publish:
    runs-on: windows-latest
    needs:
      - find_matrix
      - create_release
    if: ${{ always() && fromJSON(needs.find_matrix.outputs.json_str).modrinth.publish }}
    # POWERSHELL CANNOT WRITE VARIABLES
    defaults:
      run:
        shell: bash
    env:
      IS_RELEASE: 'true'
      PLATFORM: 'modrinth'
    strategy:
      matrix:
        mc_ver: ${{ fromJSON(needs.find_matrix.outputs.json_str).modrinth.mc_vers }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: pip requirements
        run: pip install -r requirements.txt
      - name: get data
        id: data
        run: |
          echo "dir=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].dir_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "ver=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].ver_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "type=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].type_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
      - name: export
        run: ${{ format('python -m script export --platform {0} --version {1}', env.PLATFORM, steps.data.outputs.dir) }}
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ccYQOriP
          modrinth-token: ${{ secrets.MR_TOKEN }}

          github-token: ${{ secrets.GH_TOKEN }}
          github-tag: ${{ format('release/{0}', steps.data.outputs.ver) }}

          name: ${{ format('Redstone Toolkit v{0}', steps.data.outputs.ver) }}
          files: export/*.(mrpack|zip)
          loaders: fabric
          version: ${{ format('{0}+mc{1}', steps.data.outputs.ver, matrix.mc_ver) }}
          version-type: ${{ steps.data.outputs.type }}
          game-versions: ${{ matrix.mc_ver }}
          changelog-file: changelog.md
          game-version-filter: none

  curseforge_publish:
    runs-on: windows-latest
    needs:
      - find_matrix
      - create_release
#    if: ${{ always() && fromJSON(needs.find_matrix.outputs.json_str).curseforge.publish }}
    if: false
    # POWERSHELL CANNOT WRITE VARIABLES
    defaults:
      run:
        shell: bash
    env:
      IS_RELEASE: 'true'
      PLATFORM: 'curseforge'
    strategy:
      matrix:
        mc_ver: ${{ fromJSON(needs.find_matrix.outputs.json_str).curseforge.mc_vers }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: pip requirements
        run: pip install -r requirements.txt
      - name: get data
        id: data
        run: |
          echo "dir=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].dir_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "ver=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].ver_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "type=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].type_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
      - name: export
        run: ${{ format('python -m script export --platform {0} --version {1}', env.PLATFORM, steps.data.outputs.dir) }}
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1449021
          curseforge-token: ${{ secrets.CF_TOKEN }}

          github-token: ${{ secrets.GH_TOKEN }}
          github-tag: ${{ format('release/{0}', steps.data.outputs.ver) }}

          name: ${{ format('Redstone Toolkit v{0}', steps.data.outputs.ver) }}
          files: export/*.(mrpack|zip)
          loaders: fabric
          version: ${{ format('{0}+mc{1}', steps.data.outputs.ver, matrix.mc_ver) }}
          version-type: ${{ steps.data.outputs.type }}
          game-versions: ${{ matrix.mc_ver }}
          changelog-file: changelog.md
          game-version-filter: none
          
          fail-mode: warn